"""Synthesis/Tutor node — Socratic step + final ranked differential.

Flow:
  1. interrupt() → suspends graph, sends a ranking question to the student.
     The UI calls graph.invoke(Command(resume=student_answer), config=config).
  2. LLM receives full pipeline context + student's own ranking.
  3. LLM produces: ranked differential, workup plan, Socratic feedback
     (respectful comparison of student's vs system's ranking).
  4. Citations are attached programmatically from state.evidence — the LLM
     never fabricates identifiers. Grounding check: assert_citations_grounded().

Requires a LangGraph checkpointer + thread_id in the invoke config for the
interrupt to work (ADR-0005). Without a checkpointer the graph runs without
pausing (interrupt raises GraphInterruptException which is caught by
build_graph tests using MemorySaver).
"""

from __future__ import annotations

from langgraph.types import interrupt
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from meddx.llm import model_for_agent
from meddx.prompts import load_prompt
from meddx.rag.citations import assert_citations_grounded
from meddx.schemas import (
    Citation,
    DiagnosticState,
    Phase,
    RankedHypothesis,
    SynthesisResult,
)


# ---------------------------------------------------------------------------
# LLM output schema — citations are NOT generated by the LLM (they come
# from state.evidence) so no citation fields appear here.
# ---------------------------------------------------------------------------

class _RankedEntry(BaseModel):
    hypothesis_id: str = Field(description="Exact hypothesis id, e.g. 'h1'")
    rank: int = Field(description="Final rank: 1 = most likely")
    reasoning: str = Field(
        description=(
            "Clinical reasoning for this rank: reference specific case findings "
            "and retrieved evidence strength."
        )
    )
    probability_note: str = Field(
        default="",
        description="Optional brief probability estimate or note (e.g. 'high pre-test probability').",
    )


class _SynthesisLLMOutput(BaseModel):
    ranked_hypotheses: list[_RankedEntry] = Field(
        description="All hypotheses ranked 1 (most likely) to N (least likely)."
    )
    workup_plan: list[str] = Field(
        description=(
            "Ordered list of next investigations and management steps. Must include "
            "the discriminating test from the Devil's Advocate and rule-outs from "
            "the Root-Cause Agent. Keep must-not-miss conditions visible even if ranked low."
        )
    )
    evidence_summary: str = Field(
        description=(
            "Brief summary of the evidence quality supporting the top hypothesis: "
            "note if backed by meta-analysis, RCT, cohort study, or case reports."
        )
    )
    socratic_feedback: str = Field(
        description=(
            "Respectful, educational comparison of the STUDENT's ranking vs the SYSTEM's "
            "ranking. Acknowledge correct intuitions, explain discrepancies with clinical "
            "reasoning. Reply in the student's language. Do not be condescending."
        )
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _socratic_question(state: DiagnosticState) -> str:
    hyp_list = "\n".join(f"  {i+1}. {h.name}" for i, h in enumerate(state.hypotheses))
    return (
        "Before I reveal the system's analysis, please rank these hypotheses "
        "from most to least likely based on the patient case:\n\n"
        f"{hyp_list}\n\n"
        "Type your ranking (e.g. '3, 1, 5, 2, 4' or the names in order)."
    )


def _format_full_context(state: DiagnosticState, student_ranking: str) -> str:
    name_by_id = {h.id: h.name for h in state.hypotheses}

    # Patient case
    case_lines = [
        f"  {k.replace('_', ' ').title()}: {v}"
        for k, v in state.patient_case
        if v and str(v).strip()
    ]

    # Hypotheses
    hyp_lines = [
        f"  {h.id}: {h.name} ({h.organ_system})"
        + (" [MUST-NOT-MISS]" if h.is_must_not_miss else "")
        for h in state.hypotheses
    ]

    # Evidence summary
    ev_lines = []
    for ev in state.evidence:
        n = name_by_id.get(ev.hypothesis_id, ev.hypothesis_id)
        ev_lines.append(
            f"  {n}: {len(ev.supporting)} supporting "
            f"(types: {', '.join(set(c.study_type for c in ev.supporting)) or 'none'}), "
            f"{len(ev.refuting)} refuting"
        )

    # Challenge
    ch = state.challenge
    challenge_text = "  None." if not ch else (
        "  Contradictions:\n" +
        "\n".join(f"    - {c}" for c in ch.contradictions) +
        f"\n  Discriminating test: {ch.discriminating_test}"
    )

    # Root cause
    rc = state.root_cause
    rc_text = "  None." if not rc else (
        f"  All findings explained: {rc.all_findings_explained}\n"
        f"  Unexplained: {rc.unexplained_findings}\n"
        f"  Candidates: {rc.candidate_underlying_conditions}"
    )

    return "\n\n".join([
        "Patient case:\n" + "\n".join(case_lines),
        "Hypotheses (IDs for ranked_hypotheses output):\n" + "\n".join(hyp_lines),
        "Retrieved evidence:\n" + ("\n".join(ev_lines) or "  None."),
        "Devil's Advocate:\n" + challenge_text,
        "Root-Cause assessment:\n" + rc_text,
        f"Student's ranking:\n  {student_ranking}",
        f"Student language: {state.user_language}",
    ])


def _attach_citations(
    ranked: list[_RankedEntry],
    state: DiagnosticState,
) -> list[RankedHypothesis]:
    ev_by_id = {e.hypothesis_id: e for e in state.evidence}
    result = []
    for entry in ranked:
        ev = ev_by_id.get(entry.hypothesis_id)
        citations: list[Citation] = (ev.supporting + ev.refuting) if ev else []
        result.append(
            RankedHypothesis(
                hypothesis_id=entry.hypothesis_id,
                rank=entry.rank,
                probability_note=entry.probability_note or entry.reasoning[:120],
                citations=citations,
            )
        )
    return result


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------

def synthesis_node(state: DiagnosticState) -> dict:
    # 1. Socratic step — pause and ask the student to rank hypotheses first.
    #    interrupt() suspends execution; resumed by graph.invoke(Command(resume=answer)).
    student_ranking: str = interrupt(_socratic_question(state))

    # 2. Generate the synthesis with LLM.
    llm = model_for_agent("synthesis").with_structured_output(_SynthesisLLMOutput)
    system = load_prompt("synthesis")
    context = _format_full_context(state, student_ranking)

    output: _SynthesisLLMOutput = llm.invoke(
        [
            SystemMessage(content=system),
            HumanMessage(content=context),
        ]
    )

    # 3. Attach citations from state.evidence (never from LLM output).
    ranking = _attach_citations(output.ranked_hypotheses, state)

    # 4. Anti-hallucination invariant: all cited PMID/DOI must be grounded.
    retrieved = [c for ev in state.evidence for c in ev.supporting + ev.refuting]
    used = [c for r in ranking for c in r.citations]
    assert_citations_grounded(used, retrieved)

    synthesis = SynthesisResult(
        ranking=ranking,
        workup_plan=output.workup_plan,
        evidence_summary=output.evidence_summary,
        socratic_feedback=output.socratic_feedback,
    )
    return {"synthesis": synthesis, "phase": Phase.DONE}
